apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-new
  labels:
    app: app
    version: new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: new
  template:
    metadata:
      labels:
        app: app
        version: new
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

        
