apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-canary
  labels:
    app: app
    version: old
spec:
  replicas: 9
  selector:
    matchLabels:
      app: app
      version: old
  template:
    metadata:
      labels:
        app: app
        version: old
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
        
