apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: normal # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 4Gi
  volumeName: myvolume