apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secret
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: db-credentials
      optional: true
