apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secret
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: db-credentials
      optional: true
