apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probe-app
  name: probe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-app
  template:
    metadata:
      labels: 
        app: probe-app
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: app
        image: custom-app:1.0
        ports:
        - name: readiness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: readiness-port
