apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probe-app
  name: probe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-app
  template:
    metadata:
      labels: 
        app: probe-app
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx
        ports:
          containerPort: 8080
        readinessProbe:
          exec:
          command:
          - cat
          - /health
          initialDelaySeconds: 5
          periodSeconds: 5
